export const FETCH_NOW_PLAYING = "FETCH_NOW_PLAYING";
export const FETCH_POPULAR = "FETCH_POPULAR";

export const FETCH_GENRES = "FETCH_GENRES";
export const FETCH_UPCOMING = "FETCH_UPCOMING";
export const FETCH_TV_SHOWS = "FETCH_TV_SHOWS";

export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_SEARCH_MOVIES = "FETCH_SEARCH_MOVIES";
export const FETCH_GENRE_MOVIES = "FETCH_GENRE_MOVIES";

export const FECTH_RECOMMENDATIONS = "FETCH_RECOMMENDATIONS";
