export const FETCH_CONFIG = "FETCH_CONFIG";

export const FETCH_NOW_PLAYING = "FETCH_NOW_PLAYING";
export const FETCH_POPULAR = "FETCH_POPULAR";
export const FETCH_TOP_RATED = "FETCH_TOP_RATED";
export const FETCH_FINISHED = "FETCH_FINISHED";
export const TOGGLE_HEADER = "TOGGLE_HEADER";

export const FETCH_GENRES = "FETCH_GENRES";
export const FETCH_UPCOMING = "FETCH_UPCOMING";
export const FETCH_TV_SHOWS = "FETCH_TV_SHOWS";

export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_SEARCH_MOVIES = "FETCH_SEARCH_MOVIES";
export const FETCH_GENRE_MOVIES = "FETCH_GENRE_MOVIES";
export const FETCH_CREDITS = "FETCH_CREDITS";

export const FECTH_SIMILAR_MOVIES = "FETCH_SIMILAR_MOVIES";
